const ActionTypes = {
    CHUMS: 'CHUMS',
    MYCHUMS: 'MYCHUMS',
    MYCHATROOM: 'MYCHATROOM',
    MYGROUPCHATROOM: 'MYGROUPCHATROOM',
    MESSAGES: 'MESSAGES',
    RESETREDUCER: 'RESETREDUCER',
}

export default ActionTypes;
