const ActionTypes = {
    CHUMS: 'CHUMS',
    CURRENTUSER: 'CURRENTUSER',
    MYCHUMS: 'MYCHUMS',
    MYCHATROOM: 'MYCHATROOM',
    MYGROUPCHATROOM: 'MYGROUPCHATROOM',
    MESSAGES: 'MESSAGES',
    RESETREDUCER: 'RESETREDUCER',
    LOADER: 'LOADER',
}

export default ActionTypes;
